name: Action to build and publish the project as a nuget package to github package registry

on:
  push:
    branches: [dvelop-github-actions]

jobs:
  build:
    runs-on: ubuntu-latest    
    outputs: 
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }} 

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion
    #Install and calculate the new version with GitVersion  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '6.0.0'
    
    - name: Set Version
      uses: gittools/actions/gitversion/execute@v3.2.1
      id: gitversion # step id used as reference for output values
   
    - name: Show version
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
     #Build/pack the project
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack NuGet package
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${secrets.QMAPPACKAGEPUBLISHER}
      env:
        GITHUB_TOKEN: ${{ secrets.QMAPPACKAGEPUBLISHER }}
